# -*- coding: utf-8 -*-
"""6 March

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14NLOFH5oiNC-_nDAC9ZgMkXCarT9sm3t
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("data.csv")
df.head()
df.info()
df.describe()



df.isnull().sum()

df['Weight'] = df['Weight'].fillna(df['Weight'].mean())

df[['Volume','Weight','CO2']] = df[['Volume','Weight','CO2']].fillna(df[['Volume','Weight','CO2']].mean())

df['Model'] = df['Model'].fillna(df['Model'].mode()[0])

import matplotlib.pyplot as plt

df['CO2'].hist()
plt.show()

import matplotlib.pyplot as plt

df['Weight'].hist()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("data.csv")

# Summary statistics
print(df.describe())

# Missing values
print(df.isnull().sum())

# Histogram (CO2 distribution)
df['CO2'].hist()
plt.title("CO2 Distribution")
plt.xlabel("CO2 Emission")
plt.ylabel("Count")
plt.show()

# Correlation heatmap (only numeric columns)
sns.heatmap(df[['Volume','Weight','CO2']].corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()