# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHbvqeby06rHxlIm3f9Lkq1MkKTnTlo0

**Numpy - ndarray**
"""

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr1)
print(arr2)
print(arr3)

"""**Attributes of ndarray**"""

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Item size:", arr.itemsize)

"""**Basic Indexing**"""

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

"""**Slicing**"""

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

"""**Multi-dimensional Indexing**"""

import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d[1, 2])

print(arr_2d[0:2, 1:3])