# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywhBAgIe7bUJKpM6tBcipqvkzHR9eTQb

***Array Operations Element-wise Operations***
"""

import numpy as np
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr + arr2)
print(arr * arr2)
print(arr - arr2)
print(arr / arr2)

"""**Matrix Operations (Dot product)**"""

import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print(np.dot(matrix1, matrix2))

"""**3. Broadcasting**"""

import numpy as np
arr = np.array([[1, 2], [3, 4]])

print(arr + 10)

"""**Reshaping and Flattening**"""

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

"""**Flattening:**"""

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)