# -*- coding: utf-8 -*-
"""Day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fi7rd4ah_h0nlH7dnhD947z2TTLA3G8n

**Finding Missing Values in a DataFrame**
"""

import pandas as pd
import numpy as np
d = {'First Score': [100, 90, np.nan, 95],
'Second Score': [30, 45, 56, np.nan],
'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
mv = df.isnull()
print(mv)

"""**Filtering Data Based on Missing Values**"""

import pandas as pd
d = pd.read_csv("/content/employees.csv")
bool_series = pd.isnull(d["Gender"])
missing_gender_data = d[bool_series]
print(missing_gender_data)

"""**Finding Missing Values in a DataFrame**"""

import pandas as pd
import numpy as np
data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
'Age': [25, np.nan, 22, 28]}
df = pd.DataFrame(data)
# Check for missing values using isna()
print(df.isna())

"""**Identifying Non-Missing Values in a DataFrame**"""

import pandas as pd
import numpy as np
d = {'First Score': [100, 90, np.nan, 95],
'Second Score': [30, 45, 56, np.nan],
'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
nmv = df.notnull()
print(nmv)

"""**Filtering Data with Non-Missing Values**"""

import pandas as pd
d = pd.read_csv("/content/employees.csv")
nmg = pd.notnull(d["Gender"])
nmgd= d[nmg]
display(nmgd)